name: Deployment Workflow
on:
    push:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.x'

            - name: Install Dependencies
              run: npm ci

#            - name: ESLint
#              run: npm run eslint:check
#
#            - name: Stylelint
#              if: success()
#              run: npm run stylelint:check
#
#            - name: Prettier
#              if: success()
#              run: npm run prettier:check

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.x'

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build:prod

            - name: Upload Build
              if: success()
              uses: actions/upload-artifact@v1
              with:
                  name: deploy_dist
                  path: dist
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs:
            - test
            - build
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Download Build
              uses: actions/download-artifact@v1
              with:
                  name: deploy_dist

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: deploy_dist/Summer1401-FE-Team06
